baseurl: ""
url: "https://maricarmenmartingomez.github.io"
permalink: pretty
title: 'Growth Theme'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

header: 
  fixed: true 

footer:
  enable_footer: true # show/hide the entire footer
  footer_title: "Jekyll Theme"
  footer_description: "This is a premium Jekyll theme by Zerostatic"
  enable_social_media_icons: true
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: true
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: "Projects"
  footer_secondary_menu_title: "Agency"
  footer_tertiary_menu_title: ""

bottom:
  enable_bottom: false # show/hide the entire bottom (below the footer)
  enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2025 The Growth Land"
  show_rss_icon: true

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed


colors:
  #light-mode colors
  primary_bg: "#EC255A"
  primary_bg_2: "#eed2d9"
  primary_text: "#f9fafb"
  base_bg: "#ffffff"
  base_bg_2: "#ebeef0"
  base_bg_3: "#f1f3f4"
  base_text: "#191a1a"
  base_text_2: "#555555"
  logo_text: "#191a1a"
  header_text: "#191a1a"

  # dark-mode colors
  primary_bg_dark: "#EC255A"
  primary_bg_2_dark: "#eed2d9"
  primary_text_dark: "#f9fafb"
  base_bg_dark: "#121418"
  base_bg_2_dark: "#1d2026"
  base_bg_3_dark: "#24272d"
  base_text_dark: "#F4F4F5"
  base_text_2_dark: "#D1D5DB"
  logo_text_dark: "#F4F4F5"
  header_text_dark: "#F4F4F5"


fonts:
  use_google_fonts: true # if true will use external google_fonts url below
  google_fonts_url: "https://fonts.googleapis.com/css2?&family=Schibsted+Grotesk:wght@400;500&family=Open+Sans:wght@300;400;500;600;700&family=Fira+Mono&display=swap"
  use_self_hosted_fonts: true # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css
  heading: "Schibsted Grotesk"
  base: "Open Sans"
  monospace: "Fira Mono"
  logo: "Schibsted Grotesk"


plugins: []   # establecer como array vacío para evitar error en el build de Pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
